### ISSUE TITLE
coloque suas contribuições

### ISSUE THREAD

**Issue by WesleyKawan** [oLazaroCS/oLazaroCS#1]
[![Repo Card](https://github-readme-stats.vercel.app/api/pin/?username=oLazaroCS&repo=dio-lab-open-source&bg_color=000&border_color=30A3DC&show_icons=true&icon_color=30A3DC&title_color=E94D5F&text_color=FFF)](https://github.com/oLazaroCS/dio-lab-open-source)

**Comment by oLazaroCS** [comment]
Boa ideia
